---
# tasks file for roles/sampleContainerBuildProcess main
- name: Prepare Dockerfile
  ansible.builtin.include_role:
    name: docker
    tasks_from: prepareDockefile

- name: Get credentials from Vault
  ansible.builtin.include_role:
    name: vault

- name: Build, push, deploy (locally), validate and cleanup
  block:
    - name: Build and push Dockerfile
      ansible.builtin.include_role:
        name: docker

    - name: Container Deployment
      ansible.builtin.include_tasks: containerDeployment.yml

    - name: Container Validation
      ansible.builtin.include_role:
        name: docker
        tasks_from: portValidation

    - name: Url Content Validation
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: uriContentValidation
  rescue:
    - name: List instances
      ansible.builtin.include_role:
        name: azure
        tasks_from: listInstancesOfRegistry

    - name: Remove Image
      ansible.builtin.include_role:
        name: azure
        tasks_from: removeImageFromRegistry

    - ansible.builtin.fail:
        msg: Error during Build / push / deploy (locally) and validate
  always:
    - name: Stop container
      ansible.builtin.include_role:
        name: docker
        tasks_from: stop

    - name: Prune containers and volumes
      ansible.builtin.include_role:
        name: docker
        tasks_from: prune
