---
# vars file for roles/ingress
url:
  haproxy: 'https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml'
  nginx: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml'

ports:
  http: '30080'
  https: '30443'

nodePortPorts:
  nginx:
    http:
      after: 'appProtocol: http$'
      line: '      nodePort: {{ ports.http }}'
    https:
      after: 'appProtocol: https$'
      line: '      nodePort: {{ ports.https }}'
    trafficPolicy:
      after: 'type: LoadBalancer$'
      line: '  externalTrafficPolicy: Local'
    comment:
      after: 'type: LoadBalancer$'
      line: '  # so we can preserve source IP address'
  haproxy:
    http:
      after: 'targetPort: 80$'
      line: '    nodePort: {{ ports.http }}'
    https:
      after: 'targetPort: 443$'
      line: '    nodePort: {{ ports.https }}'
    trafficPolicy:
      after: 'type: LoadBalancer$'
      line: '  externalTrafficPolicy: Local'
    comment:
      after: 'type: LoadBalancer$'
      line: '  # so we can preserve source IP address'
