---
# tasks file for roles/docker logout
- name: Log out from registry "{{ repo.registry }}"
  community.docker.docker_login:
    registry: "{{ repo.registry }}"
    state: absent
  # tags: [ never ]

- name: Log out of "{{ repo.registry }}"
  containers.podman.podman_logout:
    registry: "{{ repo.registry }}"
  tags: [ never ]
