---
# tasks file for roles/docker stop
- name: Remove Docker Container
  community.docker.docker_container:
    name: "{{ deploy.name }}"
    state: absent
    container_default_behavior: no_defaults
