---
# tasks file for roles/master main
- name: Ubuntu kubernetes procedure
  ansible.builtin.include_role:
    name: ubuntu

- name: Define node as Master
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: kubernetesMaster
