---
# tasks file for roles/master main
- name: Operating System configurations
  ansible.builtin.include_role:
    # name: "{{ kubernetesConfigurations.operatingSystem }}"
    name: "{{ hostvars[inventory_hostname].ansible_distribution }}"

- name: Launch master node
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: kubeadm.yml

- name: Apply kube configurations from remote and local
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: kubeConfig.yml

- name: Apply network element for the cluster
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: "{{ kubernetesConfigurations.networkElement }}.yml"

- name: Create dashboard and cluster role usser with permissions
  ansible.builtin.include_role:
    name: dashboard

- name: Apply metrics for the cluster
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: metrics.yml

- name: Deploy serverless functions
  ansible.builtin.include_role:
    name: fission
  when: kubernetesConfigurations.servelessFunctions | default(false) | bool

- name: Create Join Script for Client
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: joinCommand.yml

- name: Remove extra label from node
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: kubernetesRoleLabels
