---
# tasks file for roles/rbac serviceAccount
- name: Create ServiceAccount for namespace "{{ rbac.serviceAccount.metadata.namespace }}"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ rbac.serviceAccount.metadata.name }}"
        namespace: "{{ rbac.serviceAccount.metadata.namespace }}"
  become: false
  connection: local
  delegate_to: localhost
