kubernetesConfigurations:
  version:
    major: "1.21"
    minor: "5"
  socket: "crio" # crio or containerd
  operatingSystem: "xUbuntu_20.04"
  networkElement: "calico" # calico, weavenet or cilium
  ingressController: "nginx" # nginx or haproxy
