kubernetesConfigurations:
  version:
    major: "1.21"
    minor: "7"
  domain: "my.k8s.cluster.com"
  socket: "crio" # crio or containerd
  networkElement: "cilium" # calico, weavenet or cilium
  ingressController: "nginx" # nginx, haproxy or kong
  servelessFunctions: false
