kubernetesConfigurations:
  version:
    major: "1.21"
    minor: "5"
  domain: "my.k8s.cluster.com"
  socket: "crio" # crio or containerd
  operatingSystem: "xUbuntu_20.04"
  networkElement: "cilium" # calico, weavenet or cilium
  ingressController: "nginx" # nginx or haproxy
  servelessFunctions: false
