kubernetesConfigurations:
  version: "1.22.1"
  socket: "crio" # crio or containerd
  crioVersion: "1.22"
  operatingSystem: "xUbuntu_20.04"

ubuntu:
  aptKey:
    containerd:
      - {
          url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg",
          state: "present",
        }
    crio:
      - {
          url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg",
          state: "present",
        }
      - {
          url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ kubernetesConfigurations.operatingSystem }}/Release.key",
          state: "present",
        }
      - { 
          url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ kubernetesConfigurations.crioVersion }}/{{ kubernetesConfigurations.operatingSystem }}/Release.key",
          state: "present",
        }
  aptRepository:
    containerd:
      - {
          repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main",
          filename: "kubernetes.list",
          state: "present",
        }
    crio:
      - { 
          repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main",
          filename: "kubernetes.list",
          state: "present",
        }
      - {
          repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ kubernetesConfigurations.operatingSystem }}/ /",
          filename: "devel:kubic:libcontainers:stable.list",
          state: "present",
        }
      - {
          repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetesConfigurations.crioVersion }}/{{ kubernetesConfigurations.operatingSystem }}/ /",
          filename: "devel:kubic:libcontainers:stable:cri-o:{{ kubernetesConfigurations.crioVersion }}.list",
          state: "present",
        }
  packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - kubelet={{ kubernetesConfigurations.version }}-00
    - kubeadm={{ kubernetesConfigurations.version }}-00
    - kubectl={{ kubernetesConfigurations.version }}-00
  socket:
    containerd:
      - containerd
    crio:
      - runc
      - crun
      - cri-o
      - cri-o-runc

kubernetes:
  directories:
    modules:
      path: "/etc/modules-load.d"
      state: "directory"
      mode: "0755"
  modules:
    - { name: "overlay", state: "present" }
    - { name: "br_netfilter", state: "present" }
  kernelParameters:
    - {
        sysctl_file: "/etc/sysctl.d/99-kubernetes-cri.conf",
        name: "net.ipv4.ip_forward",
        value: "1",
      }
    - {
        sysctl_file: "/etc/sysctl.d/99-kubernetes-cri.conf",
        name: "net.bridge.bridge-nf-call-iptables",
        value: "1",
      }
    - {
        sysctl_file: "/etc/sysctl.d/99-kubernetes-cri.conf",
        name: "net.bridge.bridge-nf-call-ip6tables",
        value: "1",
      }

containerd:
  path: "/etc/containerd"
  state: "directory"
  mode: "0755"

crio:
  confDir:
    path: "/etc/crio/crio.conf.d"
    state: "directory"
    mode: "0755"
  confFiles:
    - { src: "crio.conf", dest: "/etc/crio" }
    - { src: "containers.conf", dest: "/usr/share/containers" }
    - { src: "02-cgroup-manager.conf", dest: "/etc/crio/crio.conf.d" }
    - { src: "03-crio-crun.conf", dest: "/etc/crio/crio.conf.d" }
    - { src: "03-crio-runc.conf", dest: "/etc/crio/crio.conf.d" }
