---
# tasks file for roles/kubernetes configMap
- name: Create ConfigMap '{{ configMap.metadata.name }}' for Deployment
  kubernetes.core.k8s:
    state: "{{ deploymentState | default('present') }}"
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    template: "{{ role_path }}/templates/configMap.yml.j2"
