---
# tasks file for roles/kubernetes dockerRegistryCreateSecret
- name: Get Secret '{{ kubernetesSecret.name }}' from namespace '{{ kubeadm.cluster.namespace }}' if exists
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ kubernetesSecret.name }}"
    namespace: "{{ kubeadm.cluster.namespace }}"
    kubeconfig: "{{ playbook_dir }}/.kube/config"
  register: dockerRegistrySecret

- name: Create secret for Docker Registry if does not exist on namespace '{{ kubeadm.cluster.namespace }}'
  ansible.builtin.shell:
    cmd: |
      kubectl --kubeconfig {{ playbook_dir }}/.kube/config \
      create secret docker-registry "{{ kubernetesSecret.name }}" \
      --namespace="{{ kubeadm.cluster.namespace | default('default') }}" \
      --docker-server="{{ repo.registry }}" \
      --docker-username="{{ vaultData.username }}" \
      --docker-password="{{ vaultData.password }}" \
      --docker-email="{{ cert.email_address }}"
  when: dockerRegistrySecret.resources | length == 0

- name: Check if secret named '{{ kubernetesSecret.name }}' exists in namespace '{{ kubeadm.cluster.namespace }}' if not create it
  block:
    - name: Check if secret named '{{ kubernetesSecret.name }}' exists in namespace '{{ kubeadm.cluster.namespace }}'
      ansible.builtin.shell:
        cmd: |
          kubectl --kubeconfig {{ playbook_dir }}/.kube/config \
          get secret "{{ kubernetesSecret.name }}" \
          --namespace="{{ kubeadm.cluster.namespace | default('default') }}"
  rescue:
    - name: Create secret for Docker Registry if does not exist on namespace '{{ kubeadm.cluster.namespace }}'
      ansible.builtin.shell:
        cmd: |
          kubectl --kubeconfig {{ playbook_dir }}/.kube/config \
          create secret docker-registry "{{ kubernetesSecret.name }}" \
          --namespace="{{ kubeadm.cluster.namespace | default('default') }}" \
          --docker-server="{{ repo.registry }}" \
          --docker-username="{{ vaultData.username }}" \
          --docker-password="{{ vaultData.password }}" \
          --docker-email="{{ cert.email_address }}"
  tags: [ never ]
