---
# tasks file for roles/kubernetes dockerRegistryCreateSecret
- name: Create dockerconfigjson auth parameter
  ansible.builtin.set_fact:
    dockerConfigJsonAuth: "{{ vaultData.username }}:{{ vaultData.password }}"

- name: Create encoded dockerconfigjson auth parameter
  ansible.builtin.set_fact:
    encodedDockerConfigJsonAuth: "{{ dockerConfigJsonAuth | b64encode }}"

- name: Create dockerconfigjson with the rest of the vars
  ansible.builtin.set_fact:
    dockerConfigJson: '{"auths":{"{{ repo.registry }}":{"username":"{{ vaultData.username }}","password":"{{ vaultData.password }}","email":"{{ cert.email_address }}","auth":"{{ encodedDockerConfigJsonAuth }}"}}}'

- name: Encode with base64 dockerconfigjson
  ansible.builtin.set_fact:
    encodedDockerConfigJson: "{{ dockerConfigJson | b64encode }}"

- name: Create secret for Docker Registry if does not exist on namespace '{{ kubeadm.cluster.namespace }}'
  community.kubernetes.k8s:
    state: present
    template: "{{ role_path }}/templates/dockerRegistrySecret.j2"
    kubeconfig: "{{ playbook_dir }}/.kube/config"

- name: Get Secret '{{ kubernetesDockerRegistrySecret.name }}' from namespace '{{ kubeadm.cluster.namespace }}' if exists
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ kubernetesDockerRegistrySecret.name }}"
    namespace: "{{ kubeadm.cluster.namespace }}"
    kubeconfig: "{{ playbook_dir }}/.kube/config"
  register: dockerRegistrySecret
  tags: [ never ]

- name: Create secret for Docker Registry if does not exist on namespace '{{ kubeadm.cluster.namespace }}'
  ansible.builtin.shell:
    cmd: |
      kubectl --kubeconfig {{ playbook_dir }}/.kube/config \
      create secret docker-registry "{{ kubernetesDockerRegistrySecret.name }}" \
      --namespace="{{ kubeadm.cluster.namespace | default('default') }}" \
      --docker-server="{{ repo.registry }}" \
      --docker-username="{{ vaultData.username }}" \
      --docker-password="{{ vaultData.password }}" \
      --docker-email="{{ cert.email_address }}"
  when: dockerRegistrySecret.resources | length == 0
  tags: [ never ]

- name: Check if secret named '{{ kubernetesDockerRegistrySecret.name }}' exists in namespace '{{ kubeadm.cluster.namespace }}' if not create it
  block:
    - name: Check if secret named '{{ kubernetesDockerRegistrySecret.name }}' exists in namespace '{{ kubeadm.cluster.namespace }}'
      ansible.builtin.shell:
        cmd: |
          kubectl --kubeconfig {{ playbook_dir }}/.kube/config \
          get secret "{{ kubernetesDockerRegistrySecret.name }}" \
          --namespace="{{ kubeadm.cluster.namespace | default('default') }}"
  rescue:
    - name: Create secret for Docker Registry if does not exist on namespace '{{ kubeadm.cluster.namespace }}'
      ansible.builtin.shell:
        cmd: |
          kubectl --kubeconfig {{ playbook_dir }}/.kube/config \
          create secret docker-registry "{{ kubernetesDockerRegistrySecret.name }}" \
          --namespace="{{ kubeadm.cluster.namespace | default('default') }}" \
          --docker-server="{{ repo.registry }}" \
          --docker-username="{{ vaultData.username }}" \
          --docker-password="{{ vaultData.password }}" \
          --docker-email="{{ cert.email_address }}"
  tags: [ never ]
