---
# tasks file for roles/kubernetes kubernetesMaster
- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.shell:
    cmd: |
      kubeadm init \
      --apiserver-advertise-address="{{ node_ip }}" \
      --apiserver-cert-extra-sans="{{ node_ip }}" \
      --node-name k8s-master \
      --pod-network-cidr=192.168.0.0/16

- name: Create kube directory
  ansible.builtin.file:
    path: /home/vagrant/.kube
    owner: vagrant
    group: vagrant
    recurse: yes

- name: Setup kubeconfig for vagrant user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: "0600"

- name: Install calico pod network
  become: false
  ansible.builtin.shell:
    cmd: "kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml"

- name: Generate join command
  ansible.builtin.shell:
    cmd: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  ansible.builtin.copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "./join-command"
  delegate_to: localhost

- name: Synchronization using rsync protocol (pull)
  ansible.posix.synchronize:
    src: /home/vagrant/.kube
    dest: "{{ playbook_dir }}"
    mode: pull
