---
# tasks file for roles/kubernetes kubernetesMaster
- name: Initialize the Kubernetes cluster using kubeadm with socket Containerd
  ansible.builtin.shell:
    cmd: |
      kubeadm init \
      --apiserver-advertise-address "{{ node_ip }}" \
      --apiserver-cert-extra-sans "{{ node_ip }}" \
      --node-name k8s-master \
      --pod-network-cidr 192.168.0.0/16
  when: kubernetesConfigurations.socket == "containerd"

- name: Initialize the Kubernetes cluster using kubeadm with socket CRI-O
  ansible.builtin.shell:
    cmd: |
      kubeadm init \
      --apiserver-advertise-address "{{ node_ip }}" \
      --apiserver-cert-extra-sans "{{ node_ip }}" \
      --node-name k8s-master \
      --cri-socket unix:///var/run/crio/crio.sock \
      --pod-network-cidr 192.168.0.0/16
  when: kubernetesConfigurations.socket == "crio"

- name: Create kube directory
  ansible.builtin.file:
    path: /home/vagrant/.kube
    owner: vagrant
    group: vagrant
    recurse: yes

- name: Setup kubeconfig for vagrant user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: "0600"

- name: Install calico pod network
  become: false
  ansible.builtin.shell:
    cmd: "kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml"

- name: Generate join command
  ansible.builtin.shell:
    cmd: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file for Containerd
  become: false
  ansible.builtin.copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "{{ role_path }}/files/join-command.sh"
  when: kubernetesConfigurations.socket == "containerd"
  delegate_to: localhost

- name: Copy join command to local file for CRI-O
  become: false
  ansible.builtin.copy:
    content: "{{ join_command.stdout_lines[0] }} --cri-socket unix:///var/run/crio/crio.sock"
    dest: "{{ role_path }}/files/join-command.sh"
  when: kubernetesConfigurations.socket == "crio"
  delegate_to: localhost

- name: Pull .kube dir to local
  become: false
  ansible.posix.synchronize:
    src: /home/vagrant/.kube
    dest: "{{ playbook_dir }}"
    mode: pull
