---
# tasks file for roles/kubernetes kubeConfig
- name: Create kube directory
  ansible.builtin.file:
    path: /home/vagrant/.kube
    owner: vagrant
    group: vagrant
    recurse: yes
 
- name: Setup kubeconfig for vagrant user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: "0600"
 
- name: Pull .kube dir to localhost
  become: false
  ansible.posix.synchronize:
    src: /home/vagrant/.kube
    dest: "{{ playbook_dir }}"
    mode: pull
