---
# tasks file for roles/kubernetes kubernetesMaster
- name: Launch master node
  ansible.builtin.include_tasks: kubeadm.yml

- name: Apply kube configurations from remote and local
  ansible.builtin.include_tasks: kubeConfig.yml

- name: Apply network element for the cluster
  ansible.builtin.include_tasks: "{{ kubernetesConfigurations.networkElement }}.yml"

- name: Ingress contrroller Processes
  ansible.builtin.include_role:
    name: ingress
    tasks_from: "{{ kubernetesConfigurations.ingressController }}.yml"

- name: Create dashboard and cluster role usser with permissions
  ansible.builtin.include_tasks: dashboard.yml

- name: Apply metrics for the cluster
  ansible.builtin.include_tasks: metrics.yml

- name: Create Join Script for Client
  ansible.builtin.include_tasks: joinCommand.yml
