---
# tasks file for roles/kubernetes main
- name: Configure node ip
  ansible.builtin.lineinfile:
    create: yes
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Configure CPU and Memory for cgroups
  ansible.builtin.copy:
    src: 11-cgroups.conf
    dest: /etc/systemd/system/kubelet.service.d/11-cgroups.conf
  tags: [ never ]

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    daemon_reload: yes
    state: restarted
