---
# tasks file for roles/kubernetes main
- name: Configure node ip
  ansible.builtin.lineinfile:
    create: yes
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    daemon_reload: yes
    state: restarted
