---
# tasks file for roles/kubernetes modules
- name: Load the necessary modules for "{{ kubernetesConfigurations.socket }}"
  ansible.builtin.template:
    src: "{{ kubernetesConfigurations.socket }}.conf.j2"
    dest: "{{ kubernetes.directories.modules.path }}/{{ kubernetesConfigurations.socket }}.conf"

- name: Extend kernel functionality for Kubernetes
  community.general.modprobe:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ kubernetes.modules }}"
