---
# tasks file for roles/kubernetes namespace
- name: Create or Remove Namespace "{{ ingress.metadata.namespace }}"
  kubernetes.core.k8s:
    name: "{{ ingress.metadata.namespace }}"
    api_version: v1
    kind: Namespace
    state: "{{ namespaceState | default('present') }}"
    kubeconfig: "{{ playbook_dir }}/.kube/config"
