---
# tasks file for roles/kubernetes uriContentValidation
- name: Fail if the url '{{ domain.url }}' is not accessible
  ansible.builtin.uri:
    url: "{{ domain.urlPrefix }}://{{ domain.url }}:{{ ports[domain.urlPrefix] }}"
    return_content: yes
  register: urlContent
  until: urlContent.status == 200
  retries: 10
  delay: 5
  failed_when: domain.validation_content not in urlContent.content
  connection: local
  delegate_to: localhost
