---
# tasks file for roles/kubernetes weavenet
- name: Install weavenet pod network
  become: false
  ansible.builtin.shell:
    cmd: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&password-secret=weave-passwd&env.IPALLOC_RANGE=192.168.0.0/24"
