---
# tasks file for roles/kubernetes caCleanup
- name: Cleanup CA files
  ansible.builtin.file:
    path: "{{ role_path }}/files/{{ item }}"
    state: absent
  loop: "{{ ingress.certfiles.values() }}"
