---
# tasks file for roles/kubernetes ingressHttp
- name: Ingress deployment with 'nginx' at '{{ ingress.metadata.namespace }}' namespace
  community.kubernetes.k8s:
    state: "{{ ingressState | default('present') }}"
    kubeconfig: "{{ playbook_dir }}/.kube/config"
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ ingress.metadata.name }}"
        namespace: "{{ ingress.metadata.namespace }}"
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/rewrite-target: /
        labels:
          app.kubernetes.io/name: "{{ ingress.metadata.labels.name }}"
          app.kubernetes.io/instance: "{{ ingress.metadata.labels.instance }}"
          app.kubernetes.io/version: "{{ ingress.metadata.labels.version }}"
          app.kubernetes.io/component: "{{ ingress.metadata.labels.component }}"
          app.kubernetes.io/managed-by: "{{ ingress.metadata.labels.managed_by }}"
      spec: "{{ spec | from_yaml }}"
  vars:
    spec: |
      rules:
      - host: "{{ ingress.spec.rules.host }}"
        http:
          paths:
          - path: "{{ ingress.spec.rules.http.paths.path }}"
            pathType: "{{ ingress.spec.rules.http.paths.pathType }}"
            backend:
              service:
                name: "{{ ingress.spec.rules.http.paths.backend.service.name }}"
                port:
                  number: {{ ingress.spec.rules.http.paths.backend.service.port.number }}
