---
# tasks file for roles/ingress ingress
- name: Deploy NGINX controller
  block:
    - name: Install Helm Diff
      kubernetes.core.helm_plugin:
        state: present
        plugin_path: https://github.com/databus23/helm-diff

    - name: Remove Ingress Controller file if existed
      ansible.builtin.file:
        path: "{{ role_path }}/files/nginx.yml"
        state: absent

    - name: Get Ingress Controller
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.0/deploy/static/provider/baremetal/deploy.yaml
        dest: "{{ role_path }}/files/nginx.yml"

    - name: Update the ingress controller file with the parameters
      blockinfile:
        path: "{{ role_path }}/files/nginx.yml"
        marker: "# {mark} Node restriction"
        insertafter: "dnsPolicy: ClusterFirst"
        block: |2
                nodeSelector:
                  "node-role.kubernetes.io/ingress": "true"
                tolerations:
                - key: "dedicated"
                  operator: "Equal"
                  value: "ingress-controller"

    - name: Deploy Ingress Controller
      community.kubernetes.k8s:
        state: present
        src: nginx.yml
        kubeconfig: "{{ playbook_dir }}/.kube/config"

    - name: Label specific node(s) for dedicated ingress controller node(s)
      ansible.builtin.shell:
        cmd: |
          # kubectl --kubeconfig {{ playbook_dir }}/.kube/config label nodes {{ ansible_hostname }} node-role.kubernetes.io/worker-
          kubectl --kubeconfig {{ playbook_dir }}/.kube/config label nodes k8s-client-2 node-role.kubernetes.io/ingress="true"
          kubectl --kubeconfig {{ playbook_dir }}/.kube/config taint nodes k8s-client-2 dedicated=ingress-controller
  become: false
  connection: local
  delegate_to: localhost
