---
# tasks file for roles/ingress main
- name: Deploy '{{ kubernetesConfigurations.ingressController }}' controller
  block:
    - name: Remove Ingress Controller file if existed
      ansible.builtin.file:
        path: "{{ role_path }}/files/{{ kubernetesConfigurations.ingressController }}.yml"
        state: absent

    - name: Get Ingress Controller
      ansible.builtin.get_url:
        url: "{{ url[kubernetesConfigurations.ingressController] }}"
        dest: "{{ role_path }}/files/{{ kubernetesConfigurations.ingressController }}.yml"

    - name: Modify service type from NodePort to Loadbalancer
      ansible.builtin.replace:
        path: "{{ role_path }}/files/{{ kubernetesConfigurations.ingressController }}.yml"
        regexp: "type: NodePort$"
        replace: "type: LoadBalancer"

    - name: Add nodePort configurations
      ansible.builtin.lineinfile:
        path: "{{ role_path }}/files/{{ kubernetesConfigurations.ingressController }}.yml"
        insertafter: "{{ item.after }}"
        line: "{{ item.line }}"
      loop: "{{ nodePortPorts[kubernetesConfigurations.ingressController].values() | flatten }}"

    - name: Wait until all pods have started
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: waitForPods

    - name: Deploy Ingress Controller
      kubernetes.core.k8s:
        state: present
        src: "{{ kubernetesConfigurations.ingressController }}.yml"
        kubeconfig: "{{ playbook_dir }}/.kube/config"
  become: false
  connection: local
  delegate_to: localhost
