---
# tasks file for roles/worker main
- name: Operating System configurations
  ansible.builtin.include_role:
    # name: "{{ kubernetesConfigurations.operatingSystem }}"
    name: "{{ hostvars[inventory_hostname].ansible_distribution }}"

- name: Define node as Worker
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: kubernetesWorker

- name: Label node as worker
  ansible.builtin.include_role:
    name: kubernetes
    tasks_from: kubernetesRoleLabels
