---
# tasks file for roles/sampleContainerDeployProcess main
- name: Get credentials from Vault
  ansible.builtin.include_role:
    name: vault

- name: Deploy / validate ingress '{{ app }}' on namespace '{{ kubeadm.cluster.namespace }}'
  block:
    - name: Create Self Signed Certificate
      include_role:
        name: kubernetes
        tasks_from: cert

    - name: Create Namespace '{{ kubeadm.cluster.namespace }}'
      include_role:
        name: kubernetes
        tasks_from: namespace

    - name: Create CA Secret(s)
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: tlsSecret

    - name: Create secret for private Docker Registry
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: dockerRegistryCreateSecret

    - name: Create ConfigMap for Deployment
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: configMap

    - name: Create Deployment for '{{ app }}'
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: deployVolumesWithSecrets

    - name: Create Service '{{ service.metadata.name }}'
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: service

    - name: Create Ingress '{{ ingress.metadata.name }}'
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: "{{ kubernetesConfigurations.ingressController }}IngressHttps"

    - name: Validate uri for Webserver
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: uriContentValidation
  rescue:
    - name: Debug Logs of Deployment
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: podLogs

    - name: Rollback Deployment to last deployed working version
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: rollbackDeployment

    - name: Remove Deployment for '{{ app }}'
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: deploy
      vars:
        deploymentState: absent
      tags: [never]

    - name: Remove Service '{{ service.metadata.name }}'
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: service
      vars:
        serviceState: absent
      tags: [never]

    - name: Remove Ingress '{{ ingress.metadata.name }}'
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: "{{ kubernetesConfigurations.ingressController }}IngressHttps"
      vars:
        ingressState: absent
      tags: [never]
  always:
    - name: Cleanup CA files
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: caCleanup
